services:
  app:
    build: .
    container_name: sun-app
    depends_on:
      - mysql
    env_file:
      - .env.prod
    restart: unless-stopped
    networks:
      - sun_network


  mysql:
    image: mysql:8.0.36
    container_name: sun-mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - sun_network

networks:
  sun_network:
    name: sun_network

volumes:
  mysql_data:
    name: sun_data

